### ISSUE TITLE
Wrong path to images.

### ISSUE THREAD

**Issue by HoldenCa** [gemini-testing/html-reporter#133] opened 2018-07-11 15:37 UTC
I use configuration like in the documentation.
The problem is that images doesn't appear in html-reporter see attached picture.
I'm running `gemini gui`

```
module.exports = {
    // ...
    system: {
        plugins: {
            'html-reporter/gemini': {
                enabled: true,
                path: 'my/gemini-reports',
                defaultView: 'all',
                baseHost: 'test.com'
            }
        }
    },
    //...
}
```
![gui report - google chrome 2018-07-11 18 33 59](https://user-images.githubusercontent.com/13250475/42583302-5bface82-8539-11e8-83f0-df1de79fd0fc.png)

**Comment by jacobwindsor** [comment] 2018-11-08 10:47
A similar issue seems to occur if you're not using "images" as the output of gemini. I'm having a go at fixing both now

**Comment by jacobwindsor** [comment] 2018-11-08 11:43
My last comment was incorrect as the html-reporter copies stuff to it's own "images" folder. However, this is an issue when on a windows system so I have fixed by normalising paths

**Comment by Astimus** [comment] 2018-11-14 14:51
@HoldenCa I found workaround for this issue. I have set path property to empty string:
```
plugins: {
            'html-reporter/gemini': {
                enabled: true,
                path: '',
                defaultView: 'all',
                baseHost: 'test.com'
            }
        }
```

**Comment by SokolovAlex** [comment] 2019-03-05 11:11
it problem in logic in server-utils
https://github.com/gemini-testing/html-reporter/blob/master/lib/server-utils.js#L42

when author uses lib "path", lib generate path depends of OS. it`s necessery for server usage, but it's wrong for client usage.

the generated path uses on clinet in background.

for client path you math replace path.join
to 

components.reduce((createdPath, component) =>
    createdPath ? `${createdPath}/${component.replace('\\', '/')}` : component, '');

**Comment by wayheming** [comment] 2020-02-03 08:13
same issue

```js
var list = document.getElementsByTagName("img");
for (i = 0; i < list.length; i++) {
  list[i].src = list[i].src.replace(/%5C/g, '/');
}
```

**Comment by toonhoremans** [comment] 2020-02-10 16:47
I'm still having the same original issue and I have tried a lot of things but none of them work. Can anyone help me because I don't know what to do.
Thanks

**Comment by rafeekabid** [comment] 2020-04-08 10:13
Team,
Still I am facing html report issue using in hermione. Image is not rendered when open in crome(image is not load). But same file works well in firefox. I checked image address which is causing issue in chrome browser.
Address: "file:///D:/Temp/Test/Hermione-CSS-Regression-Testing-Example-master/my/hermione-reports/images%5C8c6858d%5CWhole%20page%5CchromeMobile~ref_0.png"

Here encoded address is populating in chrome browser like %5C, %20.
Is it fixed now?

**Closed** 2020-04-23 10:23 UTC
